### ISSUE TITLE
Discord-to-Game Chat Not Working

### ISSUE THREAD

**Issue by rileysimmons** [skythebro/SkanksAIO#2]
In-Game chat is showing up in the discord channel that is assigned.  However, when someone types in that channel in discord, what appears in-game is:

[SYSTEM] [Discord] {discord-username}:

And then nothing else.  In other words, every time someone types in discord, it spams blank messages in-game.

**Comment by skythebro** [comment]
This is due to there not being a way to do this back when I made this mod , because of gloomrot the entire server messaging system changed, and so bloodstone had to update. I think it has updated now on github so maybe I can add this functionality

**Comment by rileysimmons** [comment]
Thanks for looking at it @skythebro !  Bad timing that it was right before 1.0 release and everything broke lol.  I posted the error logs in a new issue post if you have time to take a look.  Thanks again!
