### ISSUE TITLE
Update for V Rising 1.0 Support

### ISSUE THREAD

**Issue by rileysimmons** [skythebro/SkanksAIO#3]
I know you just got done fixing a bunch of issues, but it looks like the addon isn't work with V Rising update.  I've been testing with beta version of BepinEx that works with 1.0 release and so far the discord integration isn't working at all.  Would love to see it updated. Thanks!

**Comment by rileysimmons** [comment]
If this helps, this is from the log output:

[Warning:Il2CppInterop] Method System.Threading.Tasks.Task OnMessageReceived(Discord.WebSocket.SocketUserMessage) on type SkanksAIO.App has unsupported return type System.Threading.Tasks.Task
[Warning:Il2CppInterop] Method System.Threading.Tasks.Task ClientOnMessageReceived(Discord.WebSocket.SocketMessage) on type SkanksAIO.App has unsupported return type System.Threading.Tasks.Task
[Info   :Il2CppInterop] Registered mono type SkanksAIO.App in il2cpp domain
[Warning:Il2CppInterop] Method Void add_OnRequestReceived(SkanksAIO.Web.RequestReceived) on type SkanksAIO.Web.WebBehaviour has unsupported parameter SkanksAIO.Web.RequestReceived value of type SkanksAIO.Web.RequestReceived
[Warning:Il2CppInterop] Method Void remove_OnRequestReceived(SkanksAIO.Web.RequestReceived) on type SkanksAIO.Web.WebBehaviour has unsupported parameter SkanksAIO.Web.RequestReceived value of type SkanksAIO.Web.RequestReceived
[Warning:Il2CppInterop] Method Void QueueRequest(System.Net.HttpListenerContext) on type SkanksAIO.Web.WebBehaviour has unsupported parameter System.Net.HttpListenerContext context of type System.Net.HttpListenerContext
[Info   :Il2CppInterop] Registered mono type SkanksAIO.Web.WebBehaviour in il2cpp domain
[Warning:Il2CppInterop] Method Void add_MessageReceived(MessageReceivedHandler) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter MessageReceivedHandler value of type SkanksAIO.Discord.DiscordBehaviour+MessageReceivedHandler
[Warning:Il2CppInterop] Method Void remove_MessageReceived(MessageReceivedHandler) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter MessageReceivedHandler value of type SkanksAIO.Discord.DiscordBehaviour+MessageReceivedHandler
[Warning:Il2CppInterop] Method Void add_SlashCommandExecuted(SlashCommandExecutedHandler) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter SlashCommandExecutedHandler value of type SkanksAIO.Discord.SlashCommandDelegate+SlashCommandExecutedHandler
[Warning:Il2CppInterop] Method Void remove_SlashCommandExecuted(SlashCommandExecutedHandler) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter SlashCommandExecutedHandler value of type SkanksAIO.Discord.SlashCommandDelegate+SlashCommandExecutedHandler
[Warning:Il2CppInterop] Method Void QueueMessage(Discord.WebSocket.SocketMessage) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter Discord.WebSocket.SocketMessage message of type Discord.WebSocket.SocketMessage
[Warning:Il2CppInterop] Method Void QueueSlashCommand(Discord.WebSocket.SocketSlashCommand) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter Discord.WebSocket.SocketSlashCommand command of type Discord.WebSocket.SocketSlashCommand

**Comment by skythebro** [comment]
I just released a new test release that works on vrising 1.0 [here](https://github.com/skythebro/SkanksAIO/releases/tag/1.5.0)
Like i state in the release I haven't thoroughly tested it so if there are any crashes feel free to open an issue.

**Comment by rileysimmons** [comment]
With the latest update, I'm seeing this in the logs:

[Warning:Il2CppInterop] Method Void add_OnRequestReceived(SkanksAIO.Web.RequestReceived) on type SkanksAIO.Web.WebBehaviour has unsupported parameter SkanksAIO.Web.RequestReceived value of type SkanksAIO.Web.RequestReceived

[Warning:Il2CppInterop] Method Void add_MessageReceived(MessageReceivedHandler) on type SkanksAIO.Discord.DiscordBehaviour has unsupported parameter MessageReceivedHandler value of type SkanksAIO.Discord.DiscordBehaviour+MessageReceivedHandler

And then I'm seeing these errors, even though the config file does indeed have the channel IDs configured:

[Error  :       AIO] [DiscordLib] Broadcast and Announcement channels not set, Unable to send messages.

**Comment by skythebro** [comment]
Sorry I got back to you this late but these warnings that you see I cannot do anything about that is just Il2CppInterop not recognizing the discord and web methods im using which is normal, Im pushing a new release soon with some extra error handling im hoping this will show more info if something goes wrong.

**Comment by skythebro** [comment]
Just released an update [Version 1.6.2](https://github.com/skythebro/SkanksAIO/releases/tag/1.6.2) feel free to open the issue again if it is still not working correctly
