### ISSUE TITLE
Offline Raid Protection Didnt Work

### ISSUE THREAD

**Issue by MandoDB** [skythebro/SkanksAIO#5]
The offline protection didnt work, or idk how to use it. I disconnect and we wait 10 minutes before place an siege, and my friend attack me, but he can destroy all the wall. BUT - The message "Castle under attack" with the timer disapear instantly every hit on a wall.

**Comment by skythebro** [comment]
Gonna look into this soon

**Comment by skythebro** [comment]
I'm hoping this is fixed in [Version 1.6.2](https://github.com/skythebro/SkanksAIO/releases/tag/1.6.2) feel free to open the issue again if it is still not working correctly
